config/routes.rb
Rails.application.routes.draw do
    root to: "homes#index"
    
    get "/pictures", to: "pictures#index", as: :pictures
    get "/pictures/:id", to: "pictures#show", as: :pictures_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cutmodel.rb
class Cutmodel < ApplicationRecord
    has_many :menu
    has_many :picture
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :cutmodel
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :cutmodel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
        @cutmodel_ids = Cutmodel.pluck(:id)
        @ids = @cutmodel_ids.map {|id| Picture.find_by(cutmodel_id: id).id }
        @model_ids = @ids.each_slice(3).to_a
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def index
        @q = Cutmodel.ransack(params[:q])
        @result = @q.result(distinct: true)
        @result = @result.each_slice(3).to_a
    end
    
    def show
        @cutmodel = Cutmodel.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/homes/index.html.erb
<header>
  <div class="page-header">
    <h1 class="site-name">
      <a href="/" class="site-name__double"><%= image_tag 'logo_double.png' %></a>
      <a href="/" class="site-name__sons"><%= image_tag "logo_sons.png" %></a>
    </h1>
    <nav id="nav-background" class="">
      <div class="nav-background-inner">
        <ul class="site-nav">
          <li><%= link_to "HAIR", pictures_path %></li>
          <li><%= link_to "STAFF", root_path %></li>
          <li><%= link_to "INFO", root_path %></li>
          <li><%= link_to "PRICE", root_path %></li>
          <li><%= link_to "ACCESS", root_path %></li>
          <li><%= link_to "Q&A", root_path %></li>
        </ul>
        
        <p class="site-reserve">
          各店共通<a href="#" target="_blank">オンライン予約</a>
        </p>
      </div>
    </nav><!-- / #nav-background -->

  </div><!-- / .page-header -->
    <div id="toggle_menu" class="sp">
      <div class="inner">
        <div class="menu1"></div>
        <div class="menu2"></div>
        <div class="menu3"></div>
      </div>
    </div><!-- / #toggle_menu -->
</header>



<div id="slide2">
  <ul>
    <li><%= image_tag 'top/3.jpeg' %></li>
    <li><%= image_tag 'top/14.jpeg' %></li>
    <li><%= image_tag 'top/17.jpeg' %></li>
    
  </ul>
</div>

<div class="hair-style">
    <section class="news">
      <div class="inner">
        <h2>New Style</h2>
        
            <ul class="news-list">
              <% @model_ids[0].each do |id| %>
              <li>
                <a href="pictures/<%= Picture.find(id).cutmodel_id %>">
                  <div class="photo"><%= image_tag Picture.find(id).image, class: "hair-icon" %></div>
                  <div class="detail">
                    <span class="ttl"><%= Cutmodel.find(Picture.find(id).cutmodel_id).title %></span>
                    <span class="category"><%= Cutmodel.find(Picture.find(id).cutmodel_id).category %> NEW HAIR</span><span class="date"><%= Cutmodel.find(Picture.find(id).cutmodel_id).created_at.strftime('%Y/%m/%d') %></span>
                  </div>
                </a>
              </li> 
              <% end %>
            </ul>
        
            <ul class="news-list">
              <% @model_ids[1].each do |id| %>
              <li>
                <a href="pictures/<%= Picture.find(id).cutmodel_id %>">
                  <div class="photo"><%= image_tag Picture.find(id).image, class: "hair-icon" %></div>
                  <div class="detail">
                    <span class="ttl"><%= Cutmodel.find(Picture.find(id).cutmodel_id).title %></span>
                    <span class="category"><%= Cutmodel.find(Picture.find(id).cutmodel_id).category %> NEW HAIR</span><span class="date"><%= Cutmodel.find(Picture.find(id).cutmodel_id).created_at.strftime('%Y/%m/%d') %></span>
                  </div>
                </a>
              </li> 
              <% end %>
            </ul>
        
            <ul class="news-list">
              <% @model_ids[2].each do |id| %>
              <li>
                <a href="pictures/<%= Picture.find(id).cutmodel_id %>">
                  <div class="photo"><%= image_tag Picture.find(id).image, class: "hair-icon" %></div>
                  <div class="detail">
                    <span class="ttl"><%= Cutmodel.find(Picture.find(id).cutmodel_id).title %></span>
                    <span class="category"><%= Cutmodel.find(Picture.find(id).cutmodel_id).category %> NEW HAIR</span><span class="date"><%= Cutmodel.find(Picture.find(id).cutmodel_id).created_at.strftime('%Y/%m/%d') %></span>
                  </div>
                </a>
              </li> 
              <% end %>
            </ul>
      <div class="btn"><a href="/pictures">VIEW ALL &gt;</a></div>
      </div>
      
    </section>
</div>

<section id="staff"> 
      <h2>stylist</h2>
      <div class="staff_img"><a href="#"><%= image_tag "staff.jpeg", height: '280px', width: "670px" %></a></div>
</section>

<br><br><br>

<div id="footer-wrapper">
<footer>
    <h2><span class="copy function_LH_italic">Omotesando HAIR BRAND</span></h2>
    <div class="sec01">
      <div class="salon">
        <h3>Double</h3>
        <p>
          東京都XXXXXXXXXXXXX<br>
          XXXXXXXXXXXXXXXXXX１F
          <a href="tel:0334756060">03-3475-6060</a>
        </p>
      </div>
      <div class="salon">
        <h3>Double SONS</h3>
        <p>
          東京都XXXXXXXXXXX<br>
          XXXXXXXXXXXビル2F
          <a href="tel:0364506408">03-XXXX-XXXX</a>
        </p>
      </div>
    </div><!-- / .sec01 -->
    <div class="sec02">
      <nav id="salon-nav">
        <h3>店舗情報</h3>
        <ul>
          <li><a href="#">店舗アクセス</a></li>
          <li><a href="#">採用情報</a></li>
          <li><a href="#">料金のご案内</a></li>
          <li><a href="#">お知らせ</a></li>
          <li><a href="#">よくある質問</a></li>
          <li><a href="#">ウェブログ</a></li>
        </ul>
      </nav>
      <nav id="hairstyle-nav">
        <h3>髪型・ヘアスタイル</h3>
        <ul>
        <li><a href="#">ショート</a></li>
        <li><a href="#">アレンジ</a></li>
        <li><a href="#">ミディアム</a></li>
        <li><a href="#">メンズ　</a></li>
        <li><a href="#">ボブ</a></li>
        <li><a href="#">ロング</a></li>
        </ul>
      </nav>
    </div><!-- / .sec02 -->
    <div class="sec03">
      <nav id="stylist-nav">
        <h3>スタイリスト</h3>
        <ul>
 
        <li><a href="#">山下　浩二</a></li>  
        <li><a href="#">根本　貴司</a></li>  
        <li><a href="#">西村　光太郎</a></li>  
        <li><a href="#">田中　直美</a></li>  
        <li><a href="#">東内　隆之</a></li>  
        <li><a href="#">柏　佳代子</a></li>  
        <li><a href="#">内田　由美</a></li>  
        <li><a href="#">江良　友規子</a></li>  
        <li><a href="#">松山　絵美</a></li>  
        <li><a href="#">西川　綾</a></li>  
        <li><a href="#">中嶋　瑛</a></li>  
        <li><a href="#">加藤　晃稔</a></li>  
        <li><a href="#">藤咲　真季</a></li>  
        <li><a href="#">佐藤　耕哉</a></li>  
        <li><a href="#">花</a></li>  
        <li><a href="#">大谷　茜</a></li>
        <li><a href="#">中原　章義</a></li>  
        <li><a href="#">増山　聡子</a></li>  
        <li><a href="#">漆原　サチコ</a></li>  
        <li><a href="#">松井　正太</a></li>  
        <li><a href="#">土川　直人</a></li> 
       </ul>
      </nav>
    </div><!-- / .sec03 -->
  </footer>
</div>

<script>

(function($){
$(function() {
		//ヘッダーメニューボタン
	$("#toggle_menu").click(function(){
	  
		$("body").toggleClass("open");
		$(".menu1").toggleClass("menuclick1");
		$(".menu2").toggleClass("menuclick2");
		$(".menu3").toggleClass("menuclick3");
		
		if($('body').hasClass('open')) {
		} else {
			$("#nav-background").addClass('close');
			setTimeout(function() {
				$("#nav-background").removeClass('close');
			}, 500);
		}
		
	});
  
});

})(jQuery);


$(function(){
// 設定
var $interval = 5000; // 切り替わりの間隔（ミリ秒）
var $fade_speed = 1000; // フェード処理の早さ（ミリ秒）

$("#slide2 ul li").hide().css({"position":"absolute","top":0,"left":0});
$("#slide2 ul li:first").addClass("active").show();

setInterval(function(){
  //alert("aa");
var $active2 = $("#slide2 ul li.active");
var $next2 = $active2.next("li").length?$active2.next("li"):$("#slide2 ul li:first");

$active2.fadeOut($fade_speed).removeClass("active");
$next2.fadeIn($fade_speed).addClass("active");
},$interval);

});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample1</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<header>
  <div class="page-header">
    <h1 class="site-name">
      <a href="/" class="site-name__double"><%= image_tag 'logo_double.png' %></a>
      <a href="/" class="site-name__sons"><%= image_tag "logo_sons.png" %></a>
    </h1>
    <nav id="nav-background" class="">
      <div class="nav-background-inner">
        <ul class="site-nav">
          <li><%= link_to "HAIR", pictures_path %></li>
          <li><%= link_to "STAFF", root_path %></li>
          <li><%= link_to "INFO", root_path %></li>
          <li><%= link_to "PRICE", root_path %></li>
          <li><%= link_to "ACCESS", root_path %></li>
          <li><%= link_to "Q&A", root_path %></li>
        </ul>
        
        <p class="site-reserve">
          各店共通<a href="#" target="_blank">オンライン予約</a>
        </p>
      </div>
    </nav><!-- / #nav-background -->
  </div><!-- / .page-header -->
  <div id="toggle_menu" class="sp">
    <div class="inner">
      <div class="menu1"></div>
      <div class="menu2"></div>
      <div class="menu3"></div>
    </div>
  </div>
</header>

<div class="hair-index-body">
  <div class="search-form">
    <%= search_form_for @q, url: pictures_path do |f| %>
    <ul class="clearfix">
      <li class="sort-list"><%= f.radio_button :category_eq, "NEW LINE" %>NEW LINE</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "Short", class: "sort-list2" %>SHORT</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "BOB", class: "sort-list3" %>BOB</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "Medium", class: "sort-list4" %>MEDIUM</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "Long", class: "sort-list5" %>LONG</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "MENs", class: "sort-list6" %>MENs</li>
      <li class="sort-list"><%= f.radio_button :category_eq, "ARRENGE", class: "sort-list7" %>ARRENGE</li>
    
      <li class="sort-submit"><%= f.submit "絞り込む", class: "submit" %></li>
    </ul>
    <% end %>
  </div>
  
  <h2 id="ttl-list"><%= image_tag "category_newline.png", height: '50px', width: "196px" %></h2>

  <div class="image-all">
    <% if !@result[0].nil? %>
    <table align="center">
        <tr>
          <% @result[0].each do |result| %>
            <td><%= link_to image_tag(Picture.find_by(cutmodel_id: result.id).image, class:"hair-picture"), pictures_show_path(result.id) %></td>
          <% end %>
        </tr>
    </table>
    <% end %>
    
    <% if !@result[1].nil? %>
    <table align="center">
        <tr>
          <% @result[1].each do |result| %>
            <td><%= link_to image_tag(Picture.find_by(cutmodel_id: result.id).image, class:"hair-picture"), pictures_show_path(result.id) %></td>
          <% end %>
        </tr>
    </table>
    <% end %>
    
    <% if !@result[2].nil? %>
    <table align="center">
        <tr>
          <% @result[2].each do |result| %>
            <td><%= link_to image_tag(Picture.find_by(cutmodel_id: result.id).image, class:"hair-picture"), pictures_show_path(result.id) %></td>
          <% end %>
        </tr>
    </table>
    <% end %>
  </div>

</div>
<div class="btn"><a href="/pictures">VIEW ALL &gt;</a></div>

<br><br><br>

<div id="footer-wrapper">
<footer>
    <h2><li class="copy function_LH_italic">Omotesando HAIR BRAND</li></h2>
    <div class="sec01">
      <div class="salon">
        <h3>Double</h3>
        <p>
          東京都XXXXXXXXXXXXX<br>
          XXXXXXXXXXXXXXXXXX１F
          <a href="tel:0334756060">03-3475-6060</a>
        </p>
      </div>
      <div class="salon">
        <h3>Double SONS</h3>
        <p>
          東京都XXXXXXXXXXX<br>
          XXXXXXXXXXXビル2F
          <a href="tel:0364506408">03-XXXX-XXXX</a>
        </p>
      </div>
    </div><!-- / .sec01 -->
    <div class="sec02">
      <nav id="salon-nav">
        <h3>店舗情報</h3>
        <ul>
          <li><a href="#">店舗アクセス</a></li>
          <li><a href="#">採用情報</a></li>
          <li><a href="#">料金のご案内</a></li>
          <li><a href="#">お知らせ</a></li>
          <li><a href="#">よくある質問</a></li>
          <li><a href="#">ウェブログ</a></li>
        </ul>
      </nav>
      <nav id="hairstyle-nav">
        <h3>髪型・ヘアスタイル</h3>
        <ul>
        <li><a href="#">ショート</a></li>
        <li><a href="#">アレンジ</a></li>
        <li><a href="#">ミディアム</a></li>
        <li><a href="#">メンズ　</a></li>
        <li><a href="#">ボブ</a></li>
        <li><a href="#">ロング</a></li>
        </ul>
      </nav>
    </div><!-- / .sec02 -->
    <div class="sec03">
      <nav id="stylist-nav">
        <h3>スタイリスト</h3>
        <ul>
 
        <li><a href="#">山下　浩二</a></li>  
        <li><a href="#">根本　貴司</a></li>  
        <li><a href="#">西村　光太郎</a></li>  
        <li><a href="#">田中　直美</a></li>  
        <li><a href="#">東内　隆之</a></li>  
        <li><a href="#">柏　佳代子</a></li>  
        <li><a href="#">内田　由美</a></li>  
        <li><a href="#">江良　友規子</a></li>  
        <li><a href="#">松山　絵美</a></li>  
        <li><a href="#">西川　綾</a></li>  
        <li><a href="#">中嶋　瑛</a></li>  
        <li><a href="#">加藤　晃稔</a></li>  
        <li><a href="#">藤咲　真季</a></li>  
        <li><a href="#">佐藤　耕哉</a></li>  
        <li><a href="#">花</a></li>  
        <li><a href="#">大谷　茜</a></li>
        <li><a href="#">中原　章義</a></li>  
        <li><a href="#">増山　聡子</a></li>  
        <li><a href="#">漆原　サチコ</a></li>  
        <li><a href="#">松井　正太</a></li>  
        <li><a href="#">土川　直人</a></li> 
       </ul>
      </nav>
    </div><!-- / .sec03 -->
  </footer>
</div>

<script>

(function($){
$(function() {
		//ヘッダーメニューボタン
	$("#toggle_menu").click(function(){
	  
		$("body").toggleClass("open");
		$(".menu1").toggleClass("menuclick1");
		$(".menu2").toggleClass("menuclick2");
		$(".menu3").toggleClass("menuclick3");
		
		if($('body').hasClass('open')) {
		} else {
			$("#nav-background").addClass('close');
			setTimeout(function() {
				$("#nav-background").removeClass('close');
			}, 500);
		}
		
	});
  
});

})(jQuery);

</script>

app/views/pictures/show.html.erb
<header>
  <div class="page-header">
    <h1 class="site-name">
      <a href="/" class="site-name__double"><%= image_tag 'logo_double.png' %></a>
      <a href="/" class="site-name__sons"><%= image_tag "logo_sons.png" %></a>
    </h1>
    <nav id="nav-background" class="">
      <div class="nav-background-inner">
        <ul class="site-nav">
          <li><%= link_to "HAIR", pictures_path %></li>
          <li><%= link_to "STAFF", root_path %></li>
          <li><%= link_to "INFO", root_path %></li>
          <li><%= link_to "PRICE", root_path %></li>
          <li><%= link_to "ACCESS", root_path %></li>
          <li><%= link_to "Q&A", root_path %></li>
        </ul>
        
        <p class="site-reserve">
          各店共通<a href="#" target="_blank">オンライン予約</a>
        </p>
      </div>
    </nav><!-- / #nav-background -->

  </div><!-- / .page-header -->
  <div id="toggle_menu" class="sp">
    <div class="inner">
      <div class="menu1"></div>
      <div class="menu2"></div>
      <div class="menu3"></div>
    </div>
  </div><!-- / #toggle_menu -->
</header>

<div class="hair-show">
    <ul id="imagelist" class="imagelist">
    </ul>
    
    <div class="mainImage">
        <img id="mainImage">
        <div class="stylist">
          <table>
            <tr>
              <th class="stylist-title" colspan="2">Stylist</th>
            </tr>
            <tr>
              <td class="stylist-name" colspan="2"><%= @cutmodel.stylist %></td>
            </tr>
            <tr>
              <th class="price-title" colspan="2">Price</th>
            </tr>
            <% @cutmodel.menu.each do |menu| %>
            <tr>
              <td class="price">
                <%= menu.name %>
              </td>
              <td class="price">
                ￥<%= menu.price %>〜
              </td>
            </tr>
            <% end %>
          </table>
        </div>
    </div>
    
    <div id="info02-block"> 
      <h4>Style Description</h4>
      <div class="comment">
        <p style=""><%= @cutmodel.description %></p>
      </div>
      
      <h4>How to styling</h4>
      <div class="howto">
         <p><%= @cutmodel.styling %></p>
      </div>
    </div>
</div>

<br><br><br>

<div id="footer-wrapper">
<footer>
    <h2><span class="copy function_LH_italic">Omotesando HAIR BRAND</span></h2>
    <div class="sec01">
      <div class="salon">
        <h3>Double</h3>
        <p>
          東京都XXXXXXXXXXXXX<br>
          XXXXXXXXXXXXXXXXXX１F
          <a href="tel:0334756060">03-3475-6060</a>
        </p>
      </div>
      <div class="salon">
        <h3>Double SONS</h3>
        <p>
          東京都XXXXXXXXXXX<br>
          XXXXXXXXXXXビル2F
          <a href="tel:0364506408">03-XXXX-XXXX</a>
        </p>
      </div>
    </div><!-- / .sec01 -->
    <div class="sec02">
      <nav id="salon-nav">
        <h3>店舗情報</h3>
        <ul>
          <li><a href="#">店舗アクセス</a></li>
          <li><a href="#">採用情報</a></li>
          <li><a href="#">料金のご案内</a></li>
          <li><a href="#">お知らせ</a></li>
          <li><a href="#">よくある質問</a></li>
          <li><a href="#">ウェブログ</a></li>
        </ul>
      </nav>
      <nav id="hairstyle-nav">
        <h3>髪型・ヘアスタイル</h3>
        <ul>
        <li><a href="#">ショート</a></li>
        <li><a href="#">アレンジ</a></li>
        <li><a href="#">ミディアム</a></li>
        <li><a href="#">メンズ　</a></li>
        <li><a href="#">ボブ</a></li>
        <li><a href="#">ロング</a></li>
        </ul>
      </nav>
    </div><!-- / .sec02 -->
    <div class="sec03">
      <nav id="stylist-nav">
        <h3>スタイリスト</h3>
        <ul>
 
        <li><a href="#">山下　浩二</a></li>  
        <li><a href="#">根本　貴司</a></li>  
        <li><a href="#">西村　光太郎</a></li>  
        <li><a href="#">田中　直美</a></li>  
        <li><a href="#">東内　隆之</a></li>  
        <li><a href="#">柏　佳代子</a></li>  
        <li><a href="#">内田　由美</a></li>  
        <li><a href="#">江良　友規子</a></li>  
        <li><a href="#">松山　絵美</a></li>  
        <li><a href="#">西川　綾</a></li>  
        <li><a href="#">中嶋　瑛</a></li>  
        <li><a href="#">加藤　晃稔</a></li>  
        <li><a href="#">藤咲　真季</a></li>  
        <li><a href="#">佐藤　耕哉</a></li>  
        <li><a href="#">花</a></li>  
        <li><a href="#">大谷　茜</a></li>
        <li><a href="#">中原　章義</a></li>  
        <li><a href="#">増山　聡子</a></li>  
        <li><a href="#">漆原　サチコ</a></li>  
        <li><a href="#">松井　正太</a></li>  
        <li><a href="#">土川　直人</a></li> 
       </ul>
      </nav>
    </div><!-- / .sec03 -->
  </footer>
</div>
    
<script>
  
(function($){
$(function() {
		//ヘッダーメニューボタン
	$("#toggle_menu").click(function(){
	  
		$("body").toggleClass("open");
		$(".menu1").toggleClass("menuclick1");
		$(".menu2").toggleClass("menuclick2");
		$(".menu3").toggleClass("menuclick3");
		
		if($('body').hasClass('open')) {
		} else {
			$("#nav-background").addClass('close');
			setTimeout(function() {
				$("#nav-background").removeClass('close');
			}, 500);
		}
		
	});
  
});

})(jQuery);
      
var imageTotalNumber = <%= Picture.where(cutmodel_id: @cutmodel.id).length.to_i %>;
var cutModelId = <%= @cutmodel.id.to_i %>;
var mainImageElement = document.getElementById("mainImage");
var imageListElement = document.getElementById("imagelist");

mainImageElement.setAttribute("src", `/assets/model${cutModelId}/image1.jpeg`);

for (  let i = 0;  i < imageTotalNumber;  i++  ) {
 
  var liElement = document.createElement("li");
  console.log(imageListElement);
  liElement.style.backgroundImage = `url(/assets/model${cutModelId}/image${i + 1}.jpeg)`;
  
  
  liElement.addEventListener('click', () => {
    mainImageElement.setAttribute("src", `/assets/model${cutModelId}/image${i + 1}.jpeg`);
  });
  
  imageListElement.appendChild(liElement);
}
      
      
  </script